# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.4.5"

gem "rails", "~> 8.0.2.1"
gem "sprockets-rails", ">= 2.0.0"
gem "sqlite3", ">= 1.4"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# Add the ponkotsu-md-editor gem from local path
gem "ponkotsu-md-editor", path: "../ponkotsu-md-editor"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end

group :development do
  gem "web-console"
end
